Upgraded SDK to latest version
Azure-Samples/netappfiles-dotnetcore-sdk-sample pull request #3
Opened 2021-09-08 00:26 UTC by AdelGhabboun

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2021-09-08 09:01 UTC, hildurhodd approved these changes
LGTM

2021-09-15 18:28 UTC, paulomarquesc commented on CHANGELOG.md
> +*Features*
Missing .net 5 item

2021-09-15 18:29 UTC, paulomarquesc commented on src/anf-dotnetcore-sdk-sample/program.cs
> +            if (config.ShouldCleanUp)
>ShouldCleanUp [](http://example.com/codeflow?start=23&length=13)

Since the should clean up method changed, this need to be reflected in the README.md.

2021-09-15 18:30 UTC, paulomarquesc commented on src/anf-dotnetcore-sdk-sample/program.cs
> -            //Console.ResetColor();
Why the device login option was removed? This was here and documented if customer wants to used it. Unless this got broken I suggest adding it back so customers can have an example on how to use it.

2021-09-15 18:33 UTC, paulomarquesc commented
Looks like src/anf-dotnetcore-sdk-sample/_sample-appsettings.json got corrupt somehow, it is a json file and GitHub thinks it is a binary, also on CodeFlow it shows as binary:

![image](https://user-images.githubusercontent.com/17993275/133489701-69012369-b5e8-40e3-944b-083656c9201c.png)

2021-09-15 18:34 UTC, paulomarquesc requested changes
:clock1:

2021-09-15 20:37 UTC, AdelGhabboun commented on src/anf-dotnetcore-sdk-sample/program.cs
> -            //Console.ResetColor();
I don't recall removing this but will look for it and adding it back

2021-09-15 20:57 UTC, paulomarquesc approved these changes
:shipit:

2021-09-15 21:05 UTC, merged